# This is a basic workflow to help you get started with Actions

name: check-in

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 18 * * *"  # scheduled at 06:00 (UTC+8) everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkin:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Check-in
        env:
          #设置secrets的环境变量
          GENSHIN_COOKIE: ${{ secrets.GENSHIN_COOKIE }}
        run: |
          set PYTHONIOENCODING=utf-8
          python3 ./main.py
